In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
df=pd.read_csv('weight-height.csv')
df

,Gender,Weight,Height
0,1,73.847017,241.893563
1,1,68.781904,162.310473
2,1,74.110105,212.740856
3,1,71.730978,220.042470
4,1,69.881796,206.349801
...,...,...,...
9995,0,66.172652,136.777454
9996,0,67.067155,170.867906
9997,0,63.867992,128.475319
9998,0,69.034243,163.852461


In [ ]:
fig = sns.scatterplot(data=df, x='Weight',y='Height',hue='Gender')

In [ ]:
#create a dataframe with all training data except the target column
X = df.drop(columns=['Gender'])
#check that the target variable has been removed
X.head()

In [ ]:
#separate target values
y = df['Gender'].values
#view target values
y[0:5]

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
KNeighborsClassifier()

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 1)
# Fit the classifier to the data
knn.fit(X,y)

In [ ]:
#Warning: This is not a correct way of training a model, the data should be split into training and test set
#This is cheating
knn.score(X, y)

In [4]:
#split dataset into train and test data
from sklearn.model_selection import train_test_split

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

NameError: name 'X' is not defined

In [ ]:
np.sum(y_test)

In [ ]:
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 1000)
# Fit the classifier to the data
knn.fit(X_train,y_train)

In [ ]:
knn.predict([[90,180],[20,140]])

In [ ]:
knn.score(X_test,y_test)

In [ ]:
# X_test

In [ ]:
#Make predictions on the test data
predictions=knn.predict(X_test)
predictions

In [ ]:
list(zip(predictions,y_test))

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,predictions)

In [ ]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

# Fitting Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
nb=GaussianNB()
nb.fit(X_train,y_train)
nb.score(X_test,y_test)

In [ ]:
predictions=nb.predict(X_test)

In [ ]:
list(zip(predictions,y_test))

# Diabetes Data Set

In [5]:
#read in the data using pandas
df = pd.read_table('diabetesdata.txt')
#check data has been read in properly
df

,Preg,Glucose,BP,SkinThick,Insul,BMI,DPF,Age,Diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


In [6]:
#create a dataframe with all training data except the target column
X = df.drop(columns=['Diabetes'])
#check that the target variable has been removed
X

,Preg,Glucose,BP,SkinThick,Insul,BMI,DPF,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47


In [7]:
#separate target values
y = df['Diabetes'].values
#view target values
y[0:5]

array([1, 0, 1, 0, 1], dtype=int64)

In [8]:
from sklearn.neighbors import KNeighborsClassifier
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 3)
# Fit the classifier to the data
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [9]:
#Warning: This is not a correct way of training a model, the data should be split into training and test set
#This is cheating
knn.score(X, y)

0.859375

In [10]:
df['Diabetes'].value_counts()

0    500
1    268
Name: Diabetes, dtype: int64

In [11]:
268/768

0.3489583333333333

In [12]:
#split dataset into train and test data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

In [14]:
np.sum(y_train)/len(y_train)

0.3485342019543974

In [15]:
# Create KNN classifier
knn = KNeighborsClassifier(n_neighbors = 3)
# Fit the classifier to the data
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
X_test

,Preg,Glucose,BP,SkinThick,Insul,BMI,DPF,Age
488,4,99,72,17,0,25.6,0.294,28
413,1,143,74,22,61,26.2,0.256,21
112,1,89,76,34,37,31.2,0.192,23
222,7,119,0,0,0,25.2,0.209,37
711,5,126,78,27,22,29.6,0.439,40
...,...,...,...,...,...,...,...,...
139,5,105,72,29,325,36.9,0.159,28
178,5,143,78,0,0,45.0,0.190,47
654,1,106,70,28,135,34.2,0.142,22
110,3,171,72,33,135,33.3,0.199,24


In [17]:
#Make predictions on the test data
predictions=knn.predict(X_test)

In [18]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [19]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

0.6688311688311688

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
accuracy_score(y_test,predictions)

0.6688311688311688

In [23]:
knn = KNeighborsClassifier(n_neighbors = 12)
# Fit the classifier to the data
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=12)

In [24]:
#Make predictions on the test data
knn.predict(X_test)

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
      dtype=int64)

In [25]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

0.7207792207792207